update pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,11 @@
-npx biome check --write --staged
+#!/bin/sh
+set -eu
+
+if git status --short | grep --quiet '^MM'; then
+  printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
+  exit 1;
+fi
+
+npx @biomejs/biome check --write --staged --files-ignore-unknown=true --no-errors-on-unmatched
+
+git update-index --again
